### ISSUE TITLE
 Caused by: java.io.FileNotFoundException: loading.json

### ISSUE THREAD

**Issue by ronaksuchak** [mayuce/LottieAlertDialog#2]
button_loading.setOnClickListener({
            var alertDialog : LottieAlertDialog
            alertDialog= LottieAlertDialog.Builder(this, DialogTypes.TYPE_LOADING)
                    .setTitle("Loading")
                    .setDescription("Please Wait")
                    .build()
            alertDialog.setCancelable(true)
            alertDialog.show()
        })

logcat:

    Process: com.example.etech7.dilog, PID: 23070
                                                                          java.lang.IllegalStateException: Unable to parse composition
                                                                              at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:68)
                                                                              at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:66)
                                                                              at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:167)
                                                                              at com.airbnb.lottie.LottieTask.access$300(LottieTask.java:26)
                                                                              at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:142)
                                                                              at android.os.Handler.handleCallback(Handler.java:761)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                              at android.os.Looper.loop(Looper.java:156)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                           Caused by: java.io.FileNotFoundException: loading.json
                                                                              at android.content.res.AssetManager.openAsset(Native Method)
                                                                              at android.content.res.AssetManager.open(AssetManager.java:682)
                                                                              at android.content.res.AssetManager.open(AssetManager.java:656)
                                                                              at com.airbnb.lottie.LottieCompositionFactory.fromAssetSync(LottieCompositionFactory.java:100)
                                                                              at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:81)
                                                                              at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:79)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:776)

same for error and warning !!

**Comment by Dararii** [comment]
I think you should include json file in assets folder. See sample app.

**Comment by mayuce** [comment]
You need to put your assets as like shown on the sample app. Please read the readme document again 👍
